sudo: required
dist: trusty
language: c
compiler:
  - clang
  - gcc
script: make

# Inspired by https://genbattle.bitbucket.io/blog/2016/01/17/c++-travis-ci/
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
          packages:
            - clang-3.9
